# Generated by Django 6.0.1 on 2026-01-14 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number in E.164 format (e.g., +14155551234)', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in E.164 format (e.g., +14155551234)', regex='^\\+?1?\\d{9,15}$')])),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('partner', 'Partner'), ('internal', 'Internal')], max_length=10)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
                'ordering': ['-created_at'],
            },
        ),
    ]
