# Generated by Django 6.0.1 on 2026-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='professional',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='professional',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF resume file', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
