# Generated by Django 6.0.1 on 2026-01-14 15:57

from django.db import migrations


def split_full_name(apps, schema_editor):
    """Split full_name into first_name and last_name."""
    Professional = apps.get_model("professionals", "Professional")
    for professional in Professional.objects.all():
        if professional.full_name:
            parts = professional.full_name.strip().split(" ", 1)
            professional.first_name = parts[0]
            professional.last_name = parts[1] if len(parts) > 1 else ""
            professional.save()


def reverse_split(apps, schema_editor):
    """Combine first_name and last_name back to full_name."""
    Professional = apps.get_model("professionals", "Professional")
    for professional in Professional.objects.all():
        professional.full_name = (
            f"{professional.first_name} {professional.last_name}".strip()
        )
        professional.save()


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0002_add_name_fields_and_resume"),
    ]

    operations = [
        migrations.RunPython(split_full_name, reverse_split),
    ]
