# Generated by Django 6.0.1 on 2026-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_split_fullname_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='professional',
            name='first_name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='professional',
            name='last_name',
            field=models.CharField(max_length=127),
        ),
    ]
